// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/**
 * Ejemplo de configuración avanzada para el bot
 * Descomenta y personaliza según tus necesidades
 */

module.exports = {
  workshop: {
    name: 'Mi Taller CNC',
    location: 'Tu ubicación',
    email: 'contacto@taller.com',
    phone: '+34 XXX XXX XXX',
  },

  // Configuración de máquinas
  machines: {
    checkInterval: 60000, // ms entre chequeos de estado
    alertThreshold: {
      hoursWithoutMaintenance: 500, // horas sin mantenimiento
      abnormalDowntime: 3600000, // ms de inactividad
    },
  },

  // Configuración de reportes
  reports: {
    autoGenerateDaily: true,
    reportTime: '18:00', // Formato HH:mm
    retentionDays: 90, // Días para mantener reportes
  },

  // Configuración de tareas
  tasks: {
    warningDays: 2, // Avisar N días antes del vencimiento
    autoArchive: true,
    archiveDays: 30,
  },

  // Notificaciones y Alertas
  notifications: {
    enabled: true,
    channels: ['telegram'], // 'telegram', 'email', 'sms'
    alertTypes: [
      'machine_maintenance_due',
      'task_deadline',
      'production_target_missed',
      'downtime_alert',
      'machine_failure',
      'inventory_low',
      'system_error',
    ],
    sendBulletinAt: '18:00', // Hora para boletín diario
    autoAcknowledgeAfterHours: 24, // Auto reconocer después de X horas
  },

  // Monitoreo automático
  monitoring: {
    enabled: true,
    checkIntervalMs: 300000, // 5 minutos
    checks: {
      maintenance: true,
      downtime: true,
      taskDeadlines: true,
      productionTargets: true,
    },
    autoCleanupOldAlertsAfterDays: 30,
  },

  // Roles y permisos
  roles: {
    admin: {
      permissions: [
        'create_user',
        'delete_user',
        'configure_bot',
        'view_reports',
        'acknowledge_alerts',
        'resolve_alerts',
        'force_check',
      ],
    },
    operator: {
      permissions: [
        'update_task',
        'view_machine_status',
        'generate_report',
        'acknowledge_alerts',
      ],
    },
    technician: {
      permissions: [
        'update_machine',
        'log_maintenance',
        'view_reports',
        'acknowledge_alerts',
        'resolve_alerts',
      ],
    },
    viewer: {
      permissions: [
        'view_reports',
        'view_machine_status',
      ],
    },
  },

  // Umbrales personalizados
  thresholds: {
    production: {
      dailyTarget: 100, // unidades
      warningPercent: 20, // alertar si está 20% por debajo
    },
    downtime: {
      maxContinuousHours: 4, // máximo permitido
    },
    maintenance: {
      hoursInterval: 500, // revisar cada 500 horas
      daysInterval: 90, // revisar cada 90 días
    },
  },

  // Horarios de trabajo
  schedule: {
    timezone: 'Europe/Madrid',
    workHours: {
      start: '06:00',
      end: '22:00',
    },
    daysOff: ['domingo'], // Días sin producción programada
  },

  // Integración con servicios externos
  integrations: {
    slack: {
      enabled: false,
      webhookUrl: 'https://hooks.slack.com/...',
    },
    discord: {
      enabled: false,
      webhookUrl: 'https://discord.com/api/...',
    },
    email: {
      enabled: false,
      smtpServer: 'smtp.gmail.com',
      from: 'bot@taller.com',
    },
    database: {
      enabled: false,
      type: 'mongodb', // 'mongodb', 'postgresql', 'mysql'
      connectionString: 'mongodb://localhost:27017/cnc-workshop',
    },
  },

  // Logs y debugging
  logging: {
    level: 'info', // 'debug', 'info', 'warn', 'error'
    file: './logs/bot.log',
    maxSize: '10m',
    maxFiles: 5,
  },

  // Almacenamiento de datos
  storage: {
    type: 'file', // 'file', 'mongodb', 'redis'
    path: './data',
    backupInterval: 86400000, // Cada 24 horas
  },
};
